### PR TITLE
Add new badges

### PR DESCRIPTION
**Pull request by Cairo2k18**

### CODE REVIEW

**Comment by anishanne** [comment]
Christ you need a review for adding `[Code style](https://github.com/prettier/prettier)`?

**Comment by advaith1** [comment]
ree

**Comment by Cairo2k18** [comment]
> Christ you need a review for adding `[Code style](https://github.com/prettier/prettier)`?

yeah let me fix gh settings

**Comment by anishanne** [comment]
I don't know if there's an option to do "if its 10 lines or less, ignore approval requirements"

**Comment by Cairo2k18** [comment]
> I don't know if there's an option to do "if its x lines or less of changes, ignore approval requirements"

lol I just disabled it for a second and re enabled it

**Pull request merged**
