### PR TITLE
build: add the `.js` extension on `start` script

### PR DESCRIPTION
**Pull request by toolifelesstocode**
This pull request adds the missing `.js` extension in the `start` script, because Node assumes that `app` is a directory when it is a file, hence the `app.js` was added. Which finally becomes `node --max-old-space-size=8192 dist/src/app.js`.

### CODE REVIEW

**Comment by IceeMC** [comment]
Will not merge, not needed.

**Comment by toolifelesstocode** [comment]
> Will not merge, not needed.

But when executing the command, it assumes that dist/src/app is a directory, instead of a file, which will cause a MODULE_NOT_FOUND error.

**Comment by IceeMC** [comment]
Ok, but it works for us.

**Comment by toolifelesstocode** [comment]
> Ok, but it works for us.

Well, that is fair, but this was mostly made because DEL(ly) is allowed to be self-hosted by people, which is why I made this minimal fix — Which, I do understand that the self-hoster can easily fix this. And technically the extension(.js) is added to the following comamnds:
https://github.com/discordextremelist/website/blob/main/package.json#L82
https://github.com/discordextremelist/website/blob/main/package.json#L77
https://github.com/discordextremelist/website/blob/main/package.json#L6

**Comment by IceeMC** [comment]
Yes but we do not support self hosting and probably never will.

**Comment by toolifelesstocode** [comment]
> Yes but we do not support self hosting and probably never will.

Ah. Well I guess the person hosting will just have to change it themselves, which I understand, as I mentioned that it's a very minimal thing to change. Thanks for the confirmation 😊

**Comment by advaith1** [comment]
Since we haven't had any issues with this, you should probably look into why your setup is having an issue.

**Comment by toolifelesstocode** [comment]
> Since we haven't had any issues with this, you should probably look into why your setup is having an issue.

It's likely Windows, but I'm not very certain as I haven't seen whether it happens with other operating systems either.

**Pull request closed without merging**
