### PR TITLE
Updated the link for Chrome and Added Safari

### PR DESCRIPTION
**Pull request by DuckMasterAl**
1. Chrome now has a version link - chrome://version
2. I added Safari for those people...

### CODE REVIEW

**Comment by DuckMasterAl** [comment]
👀 I need approval from everyone... that's really scary 😬

**Comment by advaith1** [comment]
not necessary imo

**Comment by DuckMasterAl** [comment]
> not necessary imo

I mean the chrome thing is important since it makes it easier to find the version of chrome @advaith1

**Comment by advaith1** [comment]
@DuckMasterAl well the version is in ://help and ://version (and always has been in both)

**Comment by DuckMasterAl** [comment]
> @DuckMasterAl well the version is in both ://help and ://version (and always has been in both)

Yes but it’s easier to find it in version since it’s at the top and says “Chrome Version” @advaith1

**Pull request merged**
