### PR TITLE
Fixes important bug with login.

### PR DESCRIPTION
**Pull request by anishanne**
This Pull Request fixes a super important bug when it comes to login. You can view the code below. Note: The commit-msg was 100% a mistake and this PR **DOES NOT** rickroll people.

Since I am a super-competent developer and would never create a fake PR, you should 100% insta merge this and not check the code.

### CODE REVIEW

**Comment by anishanne** [comment]
No what? Why was this closed man? I make legit PR to improve login bro!!! @Cairo2k18 you must stop this madmans reign of terror!!!!!

**Comment by advaith1** [comment]
anish pls

**Comment by anishanne** [comment]
Pls what bro? I make very important change to your code! I fix *critical* **vulnerability**. And you just close? Like what the f bro!!

**Comment by DuckMasterAl** [comment]
@anishanne you seem to have the same issue on @labdiscord! Make sure you patch it as soon as possible.

**Review by Cairo2k18 — APPROVED** [review]
very good

**Pull request closed without merging**
