### PR TITLE
Fix for diagonal snake issue.

### PR DESCRIPTION
**Pull request by BannerBomb**
This fixes issue #92.

I made the changes but forgot to make the Pull Request earlier.

### CODE REVIEW

**Comment by BannerBomb** [comment]
I added a fix for issue #83

**Comment by advaith1** [comment]
@angeloanan @Rom1-J @TheMoksej can someone test this

**Comment by TheMoksej** [comment]
> @angeloanan @Rom1-J @TheMoksej can someone test this
where?

**Comment by TheMoksej** [comment]
If prod it's still buggy
image

**Comment by advaith1** [comment]
download his branch and run it locally? or I can run it on dev site if you want

**Review by TheMoksej — APPROVED** [review]
I - Moksej, approve that these changes fixed the mentioned issues.

**Comment by advaith1** [comment]
@BannerBomb Thanks! could you also update it in [lgbt-website](https://github.com/discordextremelist/lgbt-website)?

**Pull request merged**
